### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by erwang01**
Still need to add copyright info.

### CODE REVIEW

**Comment by erwang01** [comment]
Please advise on the copy right info and lgtm

**Review by someonejazzy — APPROVED** [review]
btw, I think we also need to add it to the readme's on here + the main repo :)

**Comment by erwang01** [comment]
Do you mean the badges / shields icons?

**Comment by someonejazzy** [comment]
> Do you mean the badges / shields icons?

No, I mean in the readme's. If you look on the main ISAACS repo on the bottom there is licensing info, we have to put the copyright statement there, and I assume similarly on this one.

**Pull request merged**
